name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      

      - name: GitHub stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=Alanlan21&show_icons=true&theme=dracula
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: GitHub trophies
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: trophies
          options: username=Alanlan21&theme=dracula&margin-w=8
          path: trophies.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git pull --rebase origin main
          
          git add *.svg
          git commit -m "Update README cards" || exit 0
          git push
